source 'https://rubygems.org'
ruby '2.2.4'
gem 'activesupport', '~> 4.2'
gem 'bundler', '~> 1.12'
gem 'puma', '~> 3.4'
gem 'rack-contrib', '~> 1.4'
gem 'rack-attack', '~> 4.4'
gem 'rack-attack-rate-limit', '~> 1.1', require: 'rack/attack/rate-limit'
gem 'sinatra', '~> 1.4'
gem 'sinatra-param', '~> 1.4', require: 'sinatra/param'
gem 'sinatra-cross_origin', '~> 0.3'
gem 'redis', '~> 3.3'
gem 'redis-activesupport', '~> 4.1'
gem 'blake2', '~> 0.5'
gem 'rbnacl-libsodium', '~> 1.0'
gem 'rbnacl', '~> 3.4'
gem 'jsender', '~> 0.2'

group :test, :development do
  gem 'ruby-prof'
end
